[phases.setup]
nixPkgs = [
  "nodejs_20",
  "chromium",
  "nss",
  "atk",
  "at-spi2-atk",
  "gtk3",
  "libdrm",
  "gbm",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "alsa-lib",
  "pango",
  "cairo"
]